export namespace HNTableColumns {
  export const OrderTableColumns = [
    'select',
    'order_no',
    'name',
    'address',
    'orders',
    'quantity',
    'price',
    'status',
    'order_time',
    'order_update',
    'action',
  ];

  export const BoughtExpandedColumns = [
    'select',
    'serialCode',
    'code',
    'name',
    'origin',
    'box',
    'kg',
    'q',
    'unitCost',
    'totalCost',
    'branch',
    'date',
    'supplier',
    'amountOwe',
    'tax',
    'category',
    'action',
  ];

  export const ComparativeTableColumns = [
    'select',
    'totalCostGoodsBought',
    'date',
    'totalCostGoodsSold',
  ];

  export const SoldTableColumns = [
    'select',
    'serialCode',
    'code',
    'name',
    'origin',
    'box',
    'kg',
    'q',
    'unitPrice',
    'totalPrice',
    'branch',
    'date',
    'customer',
    'receivable',
    'tax',
    'category',
    'action',
  ];

  export const SoldExpandedTableColumns = [
    'select',
    'serialCode',
    'code',
    'name',
    'origin',
    'box',
    'kg',
    'q',
    'unitPrice',
    'totalPrice',
    'branch',
    'date',
    'customer',
    'receivable',
    'tax',
    'category',
    'action',
  ];

  export const InventoryComparativeTableColumns = [
    'select',
    'code',
    'name',
    'dom_int',
    'origin',
    'dateBought',
    'yesterday_box',
    'yesterday_kg',
    'difference_box',
    'difference_kg',
    'today_box',
    'today_kg',
    'branch',
    'action',
  ];

  export const BoughtTableColumns = [
    'select',
    'serialCode',
    'code',
    'name',
    'origin',
    'box',
    'kg',
    'q',
    'unitCost',
    'totalCost',
    'branch',
    'date',
    'supplier',
    'amountOwe',
    'tax',
    'category',
    'action',
  ];

  export const HistoryTableColumns = [
    'select',
    'dateBought',
    'dateSold',
    'box',
    'kg',
    'cost',
    'branch',
    'serialNumber',
    'supplierName',
    'actions',
  ];

  export const LossDetailTableColumns = [
    'select',
    'original_code',
    'original_name',
    'original_origin',
    'product_code',
    'product_name',
    'product_origin',
    'loss',
    'branch',
    'amountLost',
    'implementedDate',
    'productMade',
    'action',
  ];

  export const LossOriginalTableColumns = [
    'select',
    'original_code',
    'original_name',
    'original_origin',
    'product_code',
    'product_name',
    'product_origin',
    'loss',
    'branch',
    'amountLost',
    'implementedDate',
    'productMade',
    'action',
  ];

  export const LossProductTableColumns = [
    'select',
    'original_code',
    'original_name',
    'original_origin',
    'product_code',
    'product_name',
    'product_origin',
    'loss',
    'branch',
    'amountLost',
    'implementedDate',
    'productMade',
    'action',
  ];

  export const PayableReceivableComparativeTableColumns = [
    'select',
    'totalAmountPayable',
    'amountPayed',
    'amountBought',
    'date',
    'amountSold',
    'amountReceived',
    'totalAmountReceivable',
    'branch',
  ];

  export const PayableReceivableComparativeExpandedTableColumns = [
    'select',
    'tax',
    'amountBought',
    'amountPaid',
    'amountOwe',
    'date',
    'method',
  ];

  export const PayableTableColumns = [
    'select',
    'supplier',
    'code',
    'amountBought',
    'amountPaid',
    'amountOwe',
    'lastEdited',
    'branch',
  ];

  export const ReceivableTableColumns = [
    'date',
    'customer',
    'name',
    'method',
    'received',
    'discount',
    'total',
    'bank_account',
    'notes',
    'created',
    'updated',
    'actions',
  ];

  export const OrderRowEditTableColumns = [
    'select',
    'type',
    'sku',
    'name',
    'status',
    'origin',
    'quantity',
    'pricePerUnit',
    'totalPrice',
    'serialNumber',
    'blNumber',
    'actions',
  ];

  export const JournalEntryTableColumns = [
    'business_no',
    'owner_name',
    'business_name',
    'dob',
    'email',
    'mobile_no',
    'phone_no',
    'owner_address',
    'business_address',
    'buyer_category',
    'business_type',
    'business_category',
    'business_certificate',
    'status',
    'created',
    'updated',
    'actions',
  ];

  export const CustomerTableColumns = [
    'customer_code',
    'business_no',
    'business_name',
    // 'owner_name',
    // 'dob',
    // 'email',
    'assignee',
    'mobile_no',
    // 'phone_no',
    // 'fa_no',
    // 'owner_address',
    'business_address',
    // 'notes',
    'business_type',
    'business_category',
    // 'customer_type',
    // 'customer_category',
    // 'customer_status',
    'action',
  ];

  export const CustomerExpandedColumns = [
    'owner_name',
    'dob',
    'email',
    'phone_no',
    'fax_no',
    'owner_address',
    'notes',
    'customer_type',
    'customer_category',
    'customer_status',
  ];

  export const ProductTableColumns = [
    'sku',
    'name',
    'locality',
    'origin',
    'meat_category',
    'meat',
    'part_category',
    'part',
    'grade',
    'cost',
    'price',
    'actions',
  ];

  export const ManagerTableColumns = [
    'business_no',
    'owner_name',
    'business_name',
    'dob',
    'email',
    'mobile_no',
    'phone_no',
    'owner_address',
    'business_address',
    'buyer_category',
    'business_type',
    'business_category',
    'business_certificate',
    'status',
    'created',
    'updated',
  ];
}
